baseurl = "/"
title = "Puntadas Creativas"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Sitio web de ama de casa entusiasta de las manualidades especialmente decoraciones en punto de cruz"
  copyright = "&copy;2020 Puntadas Creativas"
  sidebarAbout = [
    "Bienvenidos! Aqui encontraras diversos elementos con bordados personalizados en punto de cruz.",
    "Los diseños son personalizados con la imagen que tu desees (depende si esta disponible el patron de diseño)"
  ]
 
  # Nav links in the side bar
  [[params.navlinks]]
  name = "Inicio"
  url = "portfolio/"
  home = true


  [[params.navlinks]]
  name = "Contactenos"
  url = "contact/"

  [params.social]
  email         = "puntadacreativa@gmail.com"
  instagram     = "https://www.instagram.com/_puntadascreativas_/"
  whatsapp      = "https://api.whatsapp.com/send?phone=573219119338&text=Hola!"
