baseurl = "https://example.org/"
title = "Puntadas Creativas"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"


[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Describe your website"
  copyright = "&copy;2020 Puntadas Creativas"
  sidebarAbout = [
    "Soy una ama de casa que disfruta del punto de cruz"
  ]
 
  # Nav links in the side bar
  [[params.navlinks]]
  name = "Inicio"
  url = "portfolio/"
  home = true


  [[params.navlinks]]
  name = "Contactenos"
  url = "contact/"

  [params.social]
  email         = "puntadacreativa@gmail.com"
  instagram     = "https://www.instagram.com/_puntadascreativas_/"
  whatsapp      = "https://api.whatsapp.com/send?phone=573219119338&text=Hola!"
